### ISSUE TITLE
Recordatorio

### ISSUE THREAD

**Issue by wincus** [cmarrero01/the-wall#1]
cuando puedas, no te olvides de pasarme material de node! --grx

**Comment by cmarrero01** [comment]
@wincus Encantado:

Primero, material de JavaScript, creo que el mejor que he leído es https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions Es muy completo, tiene ejemplos y va al núcleo directo.

Este es un poco mas primitivo, pero te da referencias de sintaxis y cosas mas básicas: http://dmitrysoshnikov.com/ecmascript/javascript-the-core/

Respecto a Node.js, tenemos varias opciones:

Tenemos a este muchacho que te guía por las cuestiones básicas de node, http://book.mixu.net/node/

Ademas tenes comunidades exclusivas para el aprendizaje de node.js, como por ejemplo: http://howtonode.org/

Y para agregar, algunos repositorios en gitHub que tiene aplicaciones de ejemplo escritas en node.js exclusivas para aprender:

https://github.com/visionmedia
https://github.com/creationix
https://github.com/felixge
https://github.com/TooTallNate

Y si te gusta aprender a través de vídeos, acá te pase un par que te pueden dar el primer aprouch antes de leer otra documentación:

http://code.tutsplus.com/tutorials/nodejs-infrastructure-part-1--net-26645
http://code.tutsplus.com/tutorials/nodejs-step-by-step-introduction--net-19448
http://code.tutsplus.com/tutorials/nodejs-step-by-step-blogging-application--net-20496

Si por alguna razón, ninguna de esta documentación te sirve o es lo que buscabas, tengo una lista de libros en pdf en mi google drive, podrías acceder desde esta URL:
https://drive.google.com/folderview?id=0B_OFI7Vdid1gNHlSS3pTNVdfVms&usp=sharing
